### ISSUE TITLE
[JOSS] Statement of Need

### ISSUE THREAD

**Issue by strengejacke** [seabbs/getTBinR#69] opened 2019-02-19 12:50 UTC
Minor issue:
This issue is related to https://github.com/openjournals/joss-reviews/issues/1260

Please add a sentence to the readme that emphasizes the need of this package (e.g., there's no other package, or there's no straightforward way to get the data w/o getTBinR, ...).

**Comment by seabbs** [comment] 2019-02-19 13:00
Hi @strengejacke 

Thanks for reviewing this. 

The README currently has: "Quickly and easily import analysis ready TB burden data, from the World Health Organisation (WHO), into R. The aim of the package is to speed up access to high-quality TB burden data, using a simple R interface. Generic plotting functions are provided to allow for rapid graphical exploration of the WHO TB data. A shiny dashboard is built in to showcase package functionality. An automated report allows country level TB burden to be summarised." 

Not sure what to add here to close this issue. There is no other package but then I would hardly expect there to be for this use case - feels a little odd to explicitly point it out?

The data can be fairly straightforwardly imported by downloading, reading into R (via readr::read_csv for example) and the munging (joining + cleaning). The use case for this package is really to speed this up, make using the dataset easier (i.e interacting with the data dictionary) and embed these data into visualisations etc to make the data more accessible/ analysis more reproducible.  Personally, I would say this is stated in the above? 

Very happy to take suggestions 😄 

Thanks, 

Sam

**Comment by strengejacke** [comment] 2019-02-19 13:24
Well, it's actually not much. The readme already says

> The aim of the package is to speed up access to high-quality TB burden data, using a simple R interface

I think you need just a small sentence, probably like in the paper where you describe the target audience ("non-specialists"). So, for whom is this package for? It's really just a short addition, in order to make the paragraph in the readme look more "complete" - you of course also add a couple of sentences, if the wording looks better for you then ;-) but I don't expect you to write a complete paper here.

**Comment by seabbs** [comment] 2019-02-19 14:19
Good point! 

I have added a pull request (#70) with some changes to the README based on the draft JOSS paper (+ updated the package description). Good to look back at the README intro as it hasn't been updated since the first package release. 

Let me know if you have suggestions for improving further. 

Thanks, 

Sam

**Closed** 2019-02-19 14:33 UTC
Labels: triage
